// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// У App нет экспортируемых методов: оболочка только поднимает TorrServer и
// демон, а весь интерфейс живёт на стороне демона.
export {}
